// <auto-generated />
using Final_Project_Group_5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project_Group_5.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20230802174250_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_Project_Group_5.Models.FavoriteFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breakfast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dessert")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dinner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lunch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breakfast = "Waffles",
                            Dessert = "Ice Cream",
                            Dinner = "Pasta",
                            Lunch = "Turkey Sandwich"
                        });
                });

            modelBuilder.Entity("Final_Project_Group_5.Models.FavoriteHobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Crafts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("Movie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteHobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crafts = "Model Kit",
                            HoursPerWeek = 1,
                            Movie = "Interstellar",
                            Sport = "Boxing"
                        });
                });

            modelBuilder.Entity("Final_Project_Group_5.Models.FavoriteRestaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Italian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pizza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sandwiches")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteRestaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Italian = "Nicola's",
                            Pizza = "Dewey's",
                            Sandwiches = "Jersey Mike's",
                            Thai = "Ruthai"
                        });
                });

            modelBuilder.Entity("Final_Project_Group_5.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Birthdate")
                        .HasColumnType("int");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearintheProgram")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = 1,
                            CollegeProgram = "Software Development",
                            FirstName = "Dilpreet",
                            LastName = "Supra",
                            YearintheProgram = 2
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = 1,
                            CollegeProgram = "Software Development",
                            FirstName = "Dilpreet",
                            LastName = "Supra",
                            YearintheProgram = 2
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = 1,
                            CollegeProgram = "Software Development",
                            FirstName = "Dilpreet",
                            LastName = "Supra",
                            YearintheProgram = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
